version: v1.0

name: Deploy Pipeline
agent:
  machine:
    type: e1-standard-2
    os_image: ubuntu1804

global_job_config:
  secrets:
    - name: BODY-MEASUREMENT-FRONTEND
    - name: NETLIFY
    - name: VERCEL
  prologue:
    commands:
      - checkout
      - npm install -g npm@8.1.1
      - npm ci

blocks:
  - name: Deploy
    task:
      jobs:
        - name: "Deploy frontend to Netlify"
          commands:
            - cp .env.ci .env
            - sed -i "s|APPVERSION|$SEMAPHORE_GIT_TAG_NAME|g" .env
            - sed -i "s|BACKENDURL|$URL_BACKEND|g" .env
            - npm install netlify-cli -g
            - npm run build
            - netlify deploy -s $NETLIFY_SITE_ID --auth $NETLIFY_ACCESS_TOKEN -p --dir ./build
        - name: 'Deploy frontend to Vercel'
          commands:
            - npm install -g vercel
            - touch APPVERSION.txt
            - touch BACKENDURL.txt
            - echo $SEMAPHORE_GIT_TAG_NAME >> APPVERSION.txt
            - echo $URL_BACKEND >> BACKENDURL.txt
            - VERCEL_PROJECT_ID=$VERCEL_PROJECT_ID VERCEL_ORG_ID=$VERCEL_ORG_ID npx vercel --token $VERCEL_TOKEN env rm REACT_APP_APP_VERSION production -y
            - VERCEL_PROJECT_ID=$VERCEL_PROJECT_ID VERCEL_ORG_ID=$VERCEL_ORG_ID npx vercel --token $VERCEL_TOKEN env rm REACT_APP_BACKEND_URL production -y
            - VERCEL_PROJECT_ID=$VERCEL_PROJECT_ID VERCEL_ORG_ID=$VERCEL_ORG_ID npx vercel --token $VERCEL_TOKEN env add REACT_APP_APP_VERSION production < APPVERSION.txt
            - VERCEL_PROJECT_ID=$VERCEL_PROJECT_ID VERCEL_ORG_ID=$VERCEL_ORG_ID npx vercel --token $VERCEL_TOKEN env add REACT_APP_BACKEND_URL production < BACKENDURL.txt
            - VERCEL_PROJECT_ID=$VERCEL_PROJECT_ID VERCEL_ORG_ID=$VERCEL_ORG_ID npx vercel --token $VERCEL_TOKEN --confirm --prod

